export const uiScreenRoutes = {
  box: 'ui_box',
  collapsibles: 'ui_collapsibles',
  tabs: 'ui_tabs',
  avatar: 'ui_avatar',
  chip: 'ui_chip',
  list: 'ui_list',
  decorators: 'ui_decorators',
  input: 'ui_input',
  buttons: 'ui_buttons',
  touchable: 'ui_touchable',
  layouts: 'ui_layouts',
  menulist: 'ui_menulist',
  dialog: 'ui_dialog',
  popup: 'ui_popup',
  flatOptions: 'ui_flatOptions',
  nestedOptions: 'ui_nestedOptions',
  selections: 'ui_selections',
  icon: 'ui_icon',
  text: 'ui_text',
  textVariants: 'ui_textVariants',
  home: 'ui_home'
} as const;
